### PR TITLE
Pass data to zlib.compress as a bytes object

### PR DESCRIPTION
**Pull request by Flying-Toast**
zlib.compress needs a bytes object, but it was being passed a string in `Profile::get_profile_string()`. This caused slicing to fail if the "{profile_string}" substitution is used in start/end gcode.

### CODE REVIEW

**Comment by markwal** [comment]
Ah.  Thanks for reminding me.  I had made a change back when I looked at it earlier and I discovered a problem and hadn't got back around to it (truth is I forgot I hadn't finished).

My change is similar to yours: markwal/OctoPrint-CuraEngineLegacy@2d4eca4e18

While this fixes the throw on slice, the gcode interpreter doesn't like it when it gets to analysis:

```
  File "/home/pi/oprint3/lib/python3.7/site-packages/octoprint/util/gcodeInterpreter.py", line 565, in _parseCuraProfileString
    zlib.decompress(base64.b64decode(comment[len(prefix) :])).split(b"\b"),
zlib.error: Error -3 while decompressing data: incorrect header check
```

I believe this is because it persists it like this:
```
; CURA_OCTO_PROFILE_STRING:b'yadayada...'
```
note that it is now quoted and has a preceding b.  The previous version running under python 2 didn't do that.

**Comment by markwal** [comment]
I think all we have to do is re-decode as utf-8 the base64encoding result.  Testing that now.

**Comment by Flying-Toast** [comment]
Ah, I see. For some reason I didn’t get that gcode interpreter error when I tested?

**Comment by markwal** [comment]
> Ah, I see. For some reason I didn’t get that gcode interpreter error when I tested?

The analyzer is a background task so there can be quite a delay. Also only in the logs.

**Pull request merged**
